In [2]:
import pandas
from rdkit import Chem
from rdkit.Chem import Descriptors

In [3]:
df = pandas.read_csv('skin_irritation_cleaned.csv')
df.shape

(81, 26)

In [4]:
df.columns

Index(['Record_ID', 'Data_Type', 'Formulation_ID', 'Formulation_Name',
       'Chemical_Name', 'CASRN', 'DTXSID', 'Percent_Active_Ingredient',
       'Concentration', 'Concentration_Units', 'Mixture', 'Species',
       'Reported_Strain', 'Strain', 'Sex', 'Assay', 'Endpoint', 'Response',
       'Response_Unit', 'Reference', 'SMILES', 'Preferred_Name', 'Synonyms',
       'URL_CompTox', 'URL_CEBS', 'label'],
      dtype='str')

In [5]:
desc_total = []
for index, row in df.iterrows():
    smi = row['SMILES']
    mol = Chem.MolFromSmiles(smi)
    desc = Descriptors.CalcMolDescriptors(mol)
    desc_total.append(desc)

In [6]:
df_desc = pandas.DataFrame(desc_total)

In [7]:
df_desc

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,8.111111,8.111111,0.138889,-0.560185,0.435835,15.000000,76.095,68.031,76.052429,32,...,0,0,0,0,0,0,0,0,0,0
1,9.768009,9.768009,0.750000,0.750000,0.395123,9.125000,114.188,100.076,114.104465,48,...,0,0,0,0,0,0,0,0,4,0
2,11.291588,11.291588,0.027971,-0.036181,0.319642,10.947368,270.457,236.185,270.255880,114,...,0,0,0,0,0,0,0,0,10,0
3,8.086250,8.086250,0.027778,0.027778,0.540974,8.888889,136.191,120.063,136.109944,58,...,0,0,0,0,0,0,0,0,0,0
4,0.000000,0.000000,0.000000,0.000000,0.262038,0.000000,39.997,38.989,39.992509,8,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,5.342083,5.342083,0.178241,0.178241,0.631655,12.857143,202.338,176.130,202.193280,86,...,0,0,0,0,0,0,0,0,0,0
77,9.555556,9.555556,0.611111,-0.611111,0.398185,8.750000,78.136,72.088,78.013936,26,...,0,0,0,0,0,0,0,0,0,0
78,10.199308,10.199308,0.734074,0.734074,0.477177,9.300000,152.218,144.154,152.029586,52,...,1,0,0,0,0,0,0,0,0,0
79,8.340278,8.340278,0.402778,-1.208333,0.336832,12.000000,121.136,110.048,121.073893,50,...,0,0,0,0,0,0,0,0,0,0
80,10.612396,10.612396,0.084676,-0.790414,0.781775,10.285714,186.210,176.130,186.068080,70,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df_id = df[['Chemical_Name','SMILES','label']]

In [15]:
df_final = pandas.concat([df_id,df_desc],axis=1) #axis를 0으로 하면 어떻게 결과가 바뀔까?

In [16]:
df_final #2D descriptor를 csv file로 저장

,Chemical_Name,SMILES,label,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,Propylene glycol,CC(O)CO,0,8.111111,8.111111,0.138889,-0.560185,0.435835,15.000000,76.095,...,0,0,0,0,0,0,0,0,0,0
1,Heptanal,CCCCCCC=O,1,9.768009,9.768009,0.750000,0.750000,0.395123,9.125000,114.188,...,0,0,0,0,0,0,0,0,4,0
2,Isopropyl myristate,CCCCCCCCCCCCCC(=O)OC(C)C,0,11.291588,11.291588,0.027971,-0.036181,0.319642,10.947368,270.457,...,0,0,0,0,0,0,0,0,10,0
3,di-Propylene glycol,"C*.C*.OCCOCCO |lp:4:2,7:2,10:2,m:1:5.6,3:8.9|",0,8.086250,8.086250,0.027778,0.027778,0.540974,8.888889,136.191,...,0,0,0,0,0,0,0,0,0,0
4,Sodium hydroxide,[OH-].[Na+],1,0.000000,0.000000,0.000000,0.000000,0.262038,0.000000,39.997,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,"Hexane, 3,3-bis(methoxymethyl)-2,5-dimethyl-",COCC(COC)(CC(C)C)C(C)C,1,5.342083,5.342083,0.178241,0.178241,0.631655,12.857143,202.338,...,0,0,0,0,0,0,0,0,0,0
77,Dimethyl sulfoxide,CS(C)=O,1,9.555556,9.555556,0.611111,-0.611111,0.398185,8.750000,78.136,...,0,0,0,0,0,0,0,0,0,0
78,4-(Methylthio)benzaldehyde,CSC1=CC=C(C=O)C=C1,0,10.199308,10.199308,0.734074,0.734074,0.477177,9.300000,152.218,...,1,0,0,0,0,0,0,0,0,0
79,Tromethamine,NC(CO)(CO)CO,1,8.340278,8.340278,0.402778,-1.208333,0.336832,12.000000,121.136,...,0,0,0,0,0,0,0,0,0,0
80,1-Naphthaleneacetic acid,OC(=O)CC1=C2C=CC=CC2=CC=C1,0,10.612396,10.612396,0.084676,-0.790414,0.781775,10.285714,186.210,...,0,0,0,0,0,0,0,0,0,0

In [40]:
import numpy as np
from rdkit.Chem import AllChem

fpgen = AllChem.GetRDKitFPGenerator()

fp_total = []
for index, row in df.iterrows():
    smi = row['SMILES']
    mol = Chem.MolFromSmiles(smi)
    fp = fpgen.GetFingerprint(mol)
    fp_array = np.zeros((0,), dtype=int)
    Chem.DataStructs.ConvertToNumpyArray(fp, fp_array)
    fp_total.append(fp_array)

In [41]:
df_fp = pd.DataFrame(fp_total, columns=[f'bit_{i}' for i in range(len(fp_total[0]))])

In [42]:
df_fp #Chemical_Name, SMILES, label 컬럼 추가한 뒤 별도 csv 파일로 저장

,bit_0,bit_1,bit_2,bit_3,bit_4,bit_5,bit_6,bit_7,bit_8,bit_9,...,bit_2038,bit_2039,bit_2040,bit_2041,bit_2042,bit_2043,bit_2044,bit_2045,bit_2046,bit_2047
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
77,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
79,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
80,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [ ]:
# smiles 코드가 단일 구조가 아니라면 '.'이 포함되어 있음.
# 단일 구조가 아닌 물질들만 리스트를 확인하고, 제거해야 될 것과 제거하면 안되는 물질 구분해보기.
# 현재 대부분이 유기 화합물이기 때문에, 유기화합물이 염(salt)가 추가된 경우는, 염을 제거한 smiles 코드를 남겨야함.
# 무기화합물이라면 제거. 유효 성분이 몇개인지 확인이 어려운 경우도 제거.

In [43]:
#https://www.rdkit.org/docs/GettingStartedInPython.html#list-of-available-descriptors
#fingerprint 종류는 매우 다양, 종류별로 모두 계산해서 저장해보기

In [39]:
'''
descriptor 추가로 계산하는 방법 (https://github.com/marcabrus/VegaDescriptor-Calculation)
모델 성능을 올리기 위해 다양한 descriptor 계산 필요.

1. Descriptors vega.zip 다운받기 ( <> Code -> Download ZIP )
2. 실행 파일: prompt
(sublime으로 열어서 명령어 살펴보기, 명령어 설명은 spiegazione prompt.txt에 기재되어 있음.)
3. input 예시 (molecules.txt)
4. output 예시 (out.txt)
'''